### ISSUE TITLE
Crear enemigos nuevos

### ISSUE THREAD

**Issue by cpereiram** [Pepereiram/carpunkcho64#26]

**Comment by aab626** [comment]
1 carpuncho creeper
2 jefe (el pepe) tiene su propio issue: https://github.com/Pepereiram/carpunkcho64/issues/38

con el tomi hablamos sobre el mov de los carpinchos normales y q nos habian dicho si los animabamos para que no se vieran moviendo tan tiesos y salieron las ideas:
1. dejar los carpinchos normales arriba de un skate
2. hacer otro enemigo q funcione igual pero q sea mas rapido y tenga un jetpack (mismo movimiento pero va como flotando, en vola podrian pasasr por arriba de los autos si no es tanto webeo)
